branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: few-app-dev
global:
  application_name: few-app
  branch: null
  default_ec2_keyname: eb-fewapp
  default_platform: Python 2.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
